version: '3'

services:
  db:
    image: mysql:8.0.32
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores